# Fundamentos de las matrices NumPy
NumPy es una de las bibliotecas de Python más populares para la computación científica y el análisis de datos. Las estructuras de datos básicas en NumPy son las matrices N-dimensionales. 
Para empezar a trabajar con NumPy, primero debe instalar la biblioteca e importarla a su entorno de trabajo. 

Para instalar NumPy, abra su terminal y ejecute el siguiente comando: ``` pip install numpy ```

Es común importar NumPy con un alias, generalmente como np. Esto facilita la referencia a las funciones y objetos de NumPy en tu código. Aquí tienes cómo hacerlo:
```python
# Importar NumPy con alias
import numpy as np
```
Puedes verificar la versión de NumPy que tienes instalada en tu entorno de desarrollo utilizando el atributo __version__. Aquí tienes un ejemplo:
```python
import numpy as np
version = np.__version__
print(version)
```
Ahora que has importado NumPy y verificado su versión, estás listo para comenzar a trabajar con esta poderosa biblioteca de Python. NumPy te proporciona herramientas para realizar cálculos matemáticos y trabajar con matrices de manera eficiente.

## Creación de Matrices en NumPy
Las matrices son estructuras de datos fundamentales en **NumPy**.
En NumPy, las matrices se representan mediante el objeto `ndarray` (matriz n-dimensional). No hay que confundirlo con el tipo `list` de Python. Las listas son objetos que pueden contener elementos de distintos tipos, cosa que no ocurre en objetos array de numpy.

In [5]:
# Creación de una matriz manualmente
import numpy as np
m1d=np.array([1, 2, 3, 4, 5])
m2d=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m1d)
print("----")
print(m2d)

[1 2 3 4 5]
----
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# Matriz de ceros de tamaña 3x3
matriz_ceros = np.zeros((3, 3))
print(matriz_ceros)
print()
# Matriz de unos de tamaño 2x4
matriz_unos = np.ones((2, 4))
print(matriz_unos)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
# Matriz identidad de tamaño 4x4
matriz_identidad = np.eye(4)
print(matriz_identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
# Matriz de 3x3 con valores del 1 al 9
matriz_rango = np.arange(1, 10).reshape((3, 3))
print(matriz_rango)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


La **función arange** crea un arreglo unidimensional entre dos valores límites, utilizando un paso (o incremento) especificado. La sintaxis más general de arange es como sigue:
```python

np.arange(start, stop, step)
```
Donde start es el valor límite inferior, stop el valor límite superior y step el paso. Observa el siguiente ejemplo: ```python np.arange(1, 10, 1) ``` es equivalente a ```python array([1, 2, 3, 4, 5, 6, 7, 8, 9]) ```




In [9]:
# Matriz de tamaño 3x3 con valores aleatorios entre 0 y 1
matriz_aleatoria = np.random.randint(0, 10, size=(3,3))
print(matriz_aleatoria)

[[6 9 2]
 [2 8 0]
 [1 6 6]]


## Operaciones básicas

Llamaremos operaciones básicas con matrices a la **suma**, **resta** y **multiplicación** de matrices. Supongamos cuatro matrices A, B, C, D, definidas como sigue:

$$
A = \begin{bmatrix}
1 & 2 \\
 3 &  4\\
\end{bmatrix} ;    
B = \begin{bmatrix}
5 &  0\\
-8 & 3 \\
\end{bmatrix} ; 
C = \begin{bmatrix}
11 & 4 & 9 \\
0 & 1 & -4 \\
\end{bmatrix} ; 
D = \begin{bmatrix}
-5 & 6 \\
2 & 3 \\
12 & 1 \\
\end{bmatrix}
$$

Para crearlas en NumPy haríamos lo siguiente:
```python
A = np.array([[1,2],[3,4]])
B = np.array([[5,0],[-8,3]])
C = np.array([[11,4,9],[0,1,-4]])
D = np.array([[-5,6],[2,3],[12,1]])
```

In [10]:
#Para crearlas en NumPy haríamos lo siguiente:

A = np.array([[1,2],[3,4]])
B = np.array([[5,0],[-8,3]])
C = np.array([[11,4,9],[0,1,-4]])
D = np.array([[-5,6],[2,3],[12,1]])

print(A)
print("----------------")
print(B)
print("----------------")
print(C)
print("----------------")
print(D)

[[1 2]
 [3 4]]
----------------
[[ 5  0]
 [-8  3]]
----------------
[[11  4  9]
 [ 0  1 -4]]
----------------
[[-5  6]
 [ 2  3]
 [12  1]]


In [11]:
# Para sumar matrices utilizamos el operador +, por ejemplo, para calcular 
print (A+B)

[[ 6  2]
 [-5  7]]


La resta de matrices funciona de manera muy similar, con la consideración de que el operador involucrado en este caso es -.
Debemos recordar que la suma (y resta) de matrices es una operación que se realiza elemento a elemento, esto implica que las matrices involucradas deben ser del mismo tamaño. Si intentamos realizar una suma con matrices de diferente tamaño, entonces Python nos devolverá un mensaje de error.


In [12]:
#La multiplicación de una matriz por un escalar se puede ejecutar utilizando el operador *, por ejemplo:
print(5*D)

[[-25  30]
 [ 10  15]
 [ 60   5]]
